In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [1]:
pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=7d5c4bac6d5131e3eb4cd76ee5f0d0f23d7810e131fa221afc0364bc760f5abb
  Stored in directory: /root/.cache/pip/wheels/cd/ef/ae/073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [10]:
df=pd.read_csv(r'/content/IPL2025Batters (1).csv')
df.head()

   Players  Team  Runs Matches   Inn     No  ...  BF  SR  100s  50s  4s  6s
0      759    15    15     one  108*  54.21  ...   1   6    88   21 NaN NaN
1      717    16    16    five   73*  65.18  ...   0   5    69   38 NaN NaN
2      657    15    15   three   73*  54.75  ...   0   8    66   19 NaN NaN
3      650    15    15     two   93*  50.00  ...   0   6    62   24 NaN NaN
4      627    13    13     NaN   117  48.23  ...   1   6    56   37 NaN NaN

[5 rows x 14 columns]

In [11]:
df.Matches=df.Matches.fillna('Zero')
df

     Players  Team  Runs Matches   Inn     No  ...  BF  SR  100s  50s  4s  6s
0        759    15    15     one  108*  54.21  ...   1   6    88   21 NaN NaN
1        717    16    16    five   73*  65.18  ...   0   5    69   38 NaN NaN
2        657    15    15   three   73*  54.75  ...   0   8    66   19 NaN NaN
3        650    15    15     two   93*  50.00  ...   0   6    62   24 NaN NaN
4        627    13    13    Zero   117  48.23  ...   1   6    56   37 NaN NaN
..       ...   ...   ...     ...   ...    ...  ...  ..  ..   ...  ...  ..  ..
151        1    14     2    five    1*   6.00  ...   0   0     0    0 NaN NaN
152        1     8     2    five    1*   1.00  ...   0   0     0    0 NaN NaN
153        1     1     1    five     1   1.00  ...   0   0     0    0 NaN NaN
154        1    13     2    five     1   1.00  ...   0   0     0    0 NaN NaN
155        1     1     1    five     1   1.00  ...   0   0     0    0 NaN NaN

[156 rows x 14 columns]

In [14]:
df.Matches=df.Matches.apply(w2n.word_to_num)
df

     Players  Team  Runs  Matches   Inn     No  ...  BF  SR  100s  50s  4s  6s
0        759    15    15        1  108*  54.21  ...   1   6    88   21 NaN NaN
1        717    16    16        5   73*  65.18  ...   0   5    69   38 NaN NaN
2        657    15    15        3   73*  54.75  ...   0   8    66   19 NaN NaN
3        650    15    15        2   93*  50.00  ...   0   6    62   24 NaN NaN
4        627    13    13        0   117  48.23  ...   1   6    56   37 NaN NaN
..       ...   ...   ...      ...   ...    ...  ...  ..  ..   ...  ...  ..  ..
151        1    14     2        5    1*   6.00  ...   0   0     0    0 NaN NaN
152        1     8     2        5    1*   1.00  ...   0   0     0    0 NaN NaN
153        1     1     1        5     1   1.00  ...   0   0     0    0 NaN NaN
154        1    13     2        5     1   1.00  ...   0   0     0    0 NaN NaN
155        1     1     1        5     1   1.00  ...   0   0     0    0 NaN NaN

[156 rows x 14 columns]

In [15]:
import math
median_test_score=math.floor(df['Runs'].mean())
median_test_score

7

In [18]:
dff=df['Runs'].mean()
dff

np.float64(7.153846153846154)

In [19]:
df['Matches']=df['Matches'].fillna(dff)
df

     Players  Team  Runs  Matches   Inn     No  ...  BF  SR  100s  50s  4s  6s
0        759    15    15        1  108*  54.21  ...   1   6    88   21 NaN NaN
1        717    16    16        5   73*  65.18  ...   0   5    69   38 NaN NaN
2        657    15    15        3   73*  54.75  ...   0   8    66   19 NaN NaN
3        650    15    15        2   93*  50.00  ...   0   6    62   24 NaN NaN
4        627    13    13        0   117  48.23  ...   1   6    56   37 NaN NaN
..       ...   ...   ...      ...   ...    ...  ...  ..  ..   ...  ...  ..  ..
151        1    14     2        5    1*   6.00  ...   0   0     0    0 NaN NaN
152        1     8     2        5    1*   1.00  ...   0   0     0    0 NaN NaN
153        1     1     1        5     1   1.00  ...   0   0     0    0 NaN NaN
154        1    13     2        5     1   1.00  ...   0   0     0    0 NaN NaN
155        1     1     1        5     1   1.00  ...   0   0     0    0 NaN NaN

[156 rows x 14 columns]

In [20]:
df.columns

Index(['Players', 'Team', 'Runs', 'Matches', 'Inn', 'No', 'HS', 'AVG', 'BF',
       'SR', '100s', '50s', '4s', '6s'],
      dtype='object')

In [21]:
result=['Team',	'Runs',	'Matches']
x=df[result]
y=df['Runs']

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [23]:
x_train.shape,x_test.shape

((109, 3), (47, 3))

In [25]:
y_train.shape,y_test.shape

((109,), (47,))

In [26]:
reg=LinearRegression()

In [27]:
model=reg.fit(x_train,y_train)

In [28]:
model.predict([[7,10,9]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([10.])

In [29]:
model.score(x_train,y_train)

1.0

In [30]:
model.score(x_test,y_test)

1.0